### ISSUE TITLE
Connection timeout error with port no 25

### ISSUE THREAD

**Issue by babitabhandari** [elliotttf/valid-mails#1]
I have used your php library (smtp_validateEmail.class.php) for email validation when i used this on localhost it works but when i put this code on server it give me warning  it did not check emails are verified or not.It give me error like 

Warning: fsockopen(): unable to connect to gmail-smtp-in.l.google.com:25(Connection timed out) in /public_html/screening/recruiter/file_upload/mail/smtp_validateEma‌​il.class.php on line 155

if ($this->sock = fsockopen($host, $this->port, $errno, $errstr, (float) $timeout)) { 
stream_set_timeout($this->sock, $this->max_read_time); 
break; 
} 
}

**Comment by elliotttf** [comment]
If it worked locally but not on a server that sounds like either a port/firewall configuration problem or possibly some sort of whitelisting issue.

It's been a _long_ time since I've worked with this code though so I'm not sure. I'm happy to review and discuss any code changes you'd like to make, but I'm not actively developing on this project.

**Comment by babitabhandari** [comment]
thanx sir for reply me.Can you please solve the issue.i have checked port no 25 is open in web server by ip address using tool. I have check status of port no using this site yougetsignal.com/tools/
It is open for incoming but   not open for outgoing.how this issue can be solved.

**Comment by elliotttf** [comment]
If it's not open for outgoing traffic you'll need to either open the port yourself or coordinate with the person/organization managing the server to have the port opened.

Either way, this isn't an issue with this codebase so I'm going to close this.
